# konfiguracja do deploymentu
spring:
    datasource:
        url: jdbc:postgresql://chat-database:5432/chat
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_schema: public
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        deserialization:
            fail-on-unknown-properties: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://keycloak:8443/realms/lolmatch
    rabbitmq:
        addresses: rabbitmq
        username: guest
        password: guest
