apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: europe-central2-docker.pkg.dev/lolmatch-407019/backend-java/api-gateway
          envFrom:
            - configMapRef:
                name: api-gateway-cm
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-cm
data:
  SPRING_PROFILES_ACTIVE: dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-external
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - port: 65501
      targetPort: 8080
