apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams
spec:
  selector:
    matchLabels:
      app: teams
  template:
    metadata:
      labels:
        app: teams
    spec:
      containers:
        - name: teams
          image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/teams-service:lolmatch
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: teams-cm
          env:
            - name: SPRING_APPLICATION_NAME
              value: teams
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: http://keycloak:80/realms/lolmatch
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teams
spec:
  selector:
    app: teams
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teams-cm
data:
  SPRING_PROFILES_ACTIVE: prod
