services:
  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: postgres:${TAG}
    container_name: "database"
    platform: ${PLATFORM}
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - network
    healthcheck:
      test: "pg_isready -U postgres"

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    container_name: "rabbitmq"
    platform: ${PLATFORM}
    image: rabbitmq:${TAG}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - hostname=rabbitmq
      - RABBITMQ_FEATURE_FLAGS=implicit_default_bindings
    networks:
      - network
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"

  keycloak:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    container_name: "keycloak"
    image: keycloak:${TAG}
    platform: ${PLATFORM}
    ports:
      - "8443:8443"
      - "8444:8444"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "echo -n > /dev/tcp/127.0.0.1/8443"]
      retries: 5
      timeout: 60s
      interval: 60s

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    platform: ${PLATFORM}
    image: api-gateway:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=dev # extra logs + docker settings -> application-dev.properties
    ports:
      - '8080:8080'
    networks:
      - network
    depends_on:
      - keycloak

  calendar:
    build:
      context: .
      dockerfile: calendar/Dockerfile
    container_name: calendar
    platform: ${PLATFORM}
    image: calendar:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=prod # prod - cors na localhost:4200
    ports:
      - '8888:8888'
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  chat-service:
    build:
      context: .
      dockerfile: chat/Dockerfile
    platform: ${PLATFORM}
    container_name: "chat-service"
    image: chat-service:${TAG}
    ports:
      - '8081:8080'
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  teams-service:
    build:
      context: .
      dockerfile: teams/Dockerfile
    platform: ${PLATFORM}
    container_name: "teams-service"
    image: teams-service:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '8082:8080'
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  network:
    driver: bridge
