version: '3.8'

services:
  db-keycloak:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: postgres:${TAG}
    container_name: "keycloak-database"
    platform: ${PLATFORM}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    networks:
      - network
    healthcheck:
      test: "pg_isready -U postgres"

  db-calendar:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: postgres:${TAG}
    container_name: "calendar-database"
    platform: ${PLATFORM}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    ports:
      - "5433:5432"
    networks:
      - network
    healthcheck:
      test: "pg_isready -U postgres"

  db-chat:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: postgres:${TAG}
    container_name: "chat-database"
    platform: ${PLATFORM}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    ports:
      - "5434:5432"
    networks:
      - network
    healthcheck:
      test: "pg_isready -U postgres"

  db-teams:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: postgres:${TAG}
    container_name: "teams-database"
    platform: ${PLATFORM}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teams
    ports:
      - "5435:5432"
    networks:
      - network
    healthcheck:
      test: "pg_isready -U postgres"

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    container_name: "rabbitmq"
    platform: ${PLATFORM}
    image: rabbitmq:${TAG}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"

  keycloak:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
      # tak mozna zrobic
      # args:
      #   - AMQP_USERNAME=user
      #   - AMQP_PASSWORD=password
    container_name: "keycloak"
    image: keycloak:${TAG}
    platform: ${PLATFORM}
    ports:
      - "8443:8443"
      - "8444:8444"
    depends_on:
      db-keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "echo -n > /dev/tcp/127.0.0.1/8443"]

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    platform: ${PLATFORM}
    image: api-gateway:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8080:8080'
    networks:
      - network
    depends_on:
      - keycloak

  calendar:
    build:
      context: .
      dockerfile: calendar/Dockerfile
    container_name: calendar
    platform: ${PLATFORM}
    image: api-calendar:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8888:8888'
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      db-calendar:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  chat-service:
    build:
      context: .
      dockerfile: chat/Dockerfile
    platform: ${PLATFORM}
    container_name: "chat-service"
    image: chat-service:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '8081:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      db-chat:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  teams-service:
    build:
      context: .
      dockerfile: teams/Dockerfile
    platform: ${PLATFORM}
    container_name: "teams-service"
    image: teams-service:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8082:8080'
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      db-teams:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    platform: ${PLATFORM}
    image: discovery-server:${TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8761:8761'
    networks:
      - network

networks:
  network:
    driver: bridge

