version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    volumes:
      - ./keycloak/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - '8443:8443'
    networks:
      - network
    command:
      - "start-dev"
      - "--http-port=8443"
      - "--import-realm"
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: mysql:8.2
    container_name: keycloak-db
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - keycloak_db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - network
    healthcheck:
      test: mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}

  api-gateway:
    image: lm-api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=dev # extra logs + docker settings -> application-dev.properties
    ports:
      - '8080:8080'
    networks:
      - network
    depends_on:
      - keycloak

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local
  keycloak_db:
    driver: local