# do odpalania lokalnie poza docker compose
spring:
    application:
        name: teams-service
    datasource:
        url: jdbc:postgresql://localhost:5435/teams
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                default_schema: public
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        deserialization:
            fail-on-unknown-properties: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://keycloak:8443/realms/lolmatch
    rabbitmq:
        addresses: localhost
        username: guest
        password: guest
server:
    port: 8090
    servlet:
        context-path: /api/teams
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
