apiVersion: v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: lolmatch
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: lolmatch
    spec:
      containers:
        - name: chat
          image: chat-service:lolmatch
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: lolmatch
spec:
  selector:
    name: chat
  ports:
    - port: 8081
      targetPort: 8080
