apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: lolmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/chat-service:lolmatch
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: https://idp.lolmatch.click/realms/lolmatch
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: lolmatch
spec:
  selector:
    name: chat
  ports:
    - port: 80
      targetPort: 8080
