apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: lolmatch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lolmatch
  template:
    metadata:
      labels:
        app: lolmatch
    spec:
      containers:
        - name: chat
          image: europe-central2-docker.pkg.dev/lolmatch-407019/backend-java/chat-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: lolmatch
spec:
  selector:
    name: chat
  ports:
    - port: 8081
      targetPort: 8080
