apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: calendar
spec:
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    containers:
      - name: calendar
        image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/calendar:lolmatch
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-svc
spec:
  type: ClusterIP
  selector:
    app: calendar
  ports:
    - port: 80
      targetPort: 8888
