apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    id: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      id: keycloak
  template:
    metadata:
      labels:
        id: keycloak
    spec:
      containers:
        - name: keycloak
          image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/keycloak:lolmatch
          imagePullPolicy: Always
          env:
            - name: KC_HOSTNAME
              value: "idp.lolmatch.click"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_PROXY_HEADERS
              value: "forwarded"
            - name: KC_HOSTNAME_DEBUG
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8443
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8443
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 8443
            - name: https
              containerPort: 8444
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  selector:
    id: keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8443
    - name: https
      port: 443
      targetPort: 8444
