apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    id: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      id: keycloak
  template:
    metadata:
      labels:
        id: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak:lolmatch
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    id: keycloak
  ports:
    - port: 9090
      targetPort: 8443
