apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    id: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      id: keycloak
  template:
    metadata:
      labels:
        id: keycloak
    spec:
      containers:
        - name: keycloak
          image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/keycloak:lolmatch
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  selector:
    id: keycloak
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configuration
data:
  AMQP_HOSTNAME: "rabbitmq"
  AMQP_PORT: "5672"
  AMQP_USERNAME: "admin"
  AMQP_PASSWORD: "password"
