apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
      containers:
        - name: rabbitmq
          image: europe-central2-docker.pkg.dev/lolmatch-407019/backend-java/rabbitmq
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq
              readOnly: true
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    name: rabbitmq
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 32111
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 32110
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  user: Z3Vlc3QK
  password: Z3Vlc3QK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    loopback_users = none
    log.console = true
