apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      id: postgres
  serviceName: postgres-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        id: postgres
    spec:
      nodeSelector:
        role: database
      tolerations:
        - key: database
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: postgres
          imagePullPolicy: Always
          image: europe-central2-docker.pkg.dev/lolmatch-415913/backend-java/postgres:lolmatch
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-service
spec:
  clusterIP: None
  selector:
    id: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXMK
  password: cG9zdGdyZXMK
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    id: postgres
  ports:
    - port: 5432
      targetPort: 5432
