#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" <<-EOSQL 
    CREATE USER "${KEYCLOAK_USER}" WITH PASSWORD "${KEYCLOAK_PASSWORD}"; 
    CREATE DATABASE "${KEYCLOAK_DB}"; 
    GRANT ALL PRIVILEGES ON DATABASE "${KEYCLOAK_DB}" to "${KEYCLOAK_USER}"; 
EOSQL
