apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007
  type: NodePort
