name: Build and Push Docker Images
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: |
          docker-compose build

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker

      - name: Push Docker images to Artifact Registry
        run: |
          docker-compose push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-java
