name: Build and Push Docker Images
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install docker compose and build images
        run: |
          apt-get update && apt-get install -y docker-compose
          docker-compose build

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REPO }} --quiet

      - name: Push Docker images to Artifact Registry
        run: |
          for service in $(docker image ls --format "{{.Repository}}:{{.Tag}}"); do
            if [[ $service == *"lolmatch"* ]]; then
              echo "Pushing $service to Artifact Registry"
              docker tag $service ${{ secrets.ARTIFACT_REPO }}/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}/$service
              docker push -q ${{ secrets.ARTIFACT_REPO }}/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}/$service
            fi
          done    
