name: Provision infrastructure and deploy services on a cluster
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to be used"
        required: true
        type: environment

jobs:
  build:
    uses: ./.github/workflows/build_and_push.yaml
    secrets:
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}

  provision:
    uses: ./.github/workflows/infrastructure_provision.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}
  
  deploy:
    needs: [build, provision]
    uses: ./.github/workflows/apply_chart.yaml
