name: Deploy services on a cluster
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to be used"
        required: true
        type: choice
        options:
          - production
          - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.github/workflows/build_and_push.yml

  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/provision.yml
        with:
          environment: ${{ inputs.environment }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: provision
    steps:
      - uses: actions/checkout@v2
