name: Provision infrastructure and deploy services on a cluster
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to be used"
        required: true
        type: choice
        options:
          - production
          - development

jobs:
  build:
    uses: ./.github/workflows/build_and_push.yaml

  provision:
    uses: ./.github/workflows/infrastructure_provision.yaml
    with:
      environment: ${{ inputs.environment }}
  
  deploy:
    needs: [build, provision]
    uses: ./.github/workflows/apply_chart.yaml
