name: Deploy infrastructure on GCP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to be used"
        required: true
        type: choice
        options:
          - production
          - development
env:
  PATH_TO_TF: terraform/environments/${{ inputs.environment }}
  TF_PLAN: tfplan
  
jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: |
        terraform -chdir=$PATH_TO_TF init
    
    - name: Terraform plan
      continue-on-error: true
      run: |
        terraform -chdir=$PATH_TO_TF plan -out=${TF_PLAN} -var "project_id=${{ secrets.GCP_PROJECT_ID }}"
        terraform -chdir=$PATH_TO_TF show -json "${TF_PLAN}" | jq > ${TF_PLAN}.json

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4        
      with:
        name: tfplan
        path: ${PATH_TO_TF}/tfplan.json

    - name: Terraform format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform apply
      run: terraform -chdir=$PATH_TO_TF apply -auto-approve ${TF_PLAN}




