name: "Destroy the infrastructure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to be used"
        required: true
        type: choice
        options:
          - production
          - development
    
env:
  PATH_TO_TF: terraform/environments/${{ inputs.environment }}

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Authenticate with Google Cloud'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Terraform'
          uses: hashicorp/setup-terraform@v3

        - name: 'Terraform destroy'
          run: |
            terraform -chdir=$PATH_TO_TF destroy -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
      
        
