name: Deploy infrastructure on GCP

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Authenticate with Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: |
        cd terraform/environments/development
        terraform init
        
    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}"




